config/routes.rb
Rails.application.routes.draw do
  root "mniams#home" 
  get 'top/tips' => 'tips#top', :as => :top_tips
  get 'static_pages/News'
  get 'static_pages/About'
  get 'static_pages/Contact'
  get 'mniams/home'
  get 'mniams/favorite_list' => 'mniams#favorite_list'
  get 'tags/:tag', to: 'mniams#home', as: :tag
  get '/download_pdf/:id(.:format)' => 'mniams#show', :method => :get, :as=>:show
  get 'feed' => 'users#feed', :as => :feed_list
  get 'top' => 'mniams#top', :as => :top
  get '/filtering/(:type)/(:con)' => 'mniams#home', :as => :filtering

  devise_for :users, controllers: { registrations: 'registrations' } do
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :mniams do
    put :favorite, on: :member
    member do
      put "like", to: "mniams#upvote"
    end
  end

  resources :contacts, only: [:new, :create]
  resources :conversations do
    resources :messages
  end

  resources :tips do
    member do
      put "like", to: "tips#upvote"
    end
  end

  resources :users, :only => [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create]
end

app/models/mniam.rb
class Mniam < ActiveRecord::Base
	default_scope { order('created_at DESC') }
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://static.pexels.com/photos/2232/vegetables-italian-pizza-restaurant.jpg"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	has_many :ingredients, dependent: :destroy
	has_many :directions, dependent: :destroy

	has_many :favorite_recipes  
  has_many :favorited_by, through: :favorite_recipes, source: :mniam 

  accepts_nested_attributes_for :ingredients,
								  	reject_if: proc { |attributes| attributes['name'].blank? },
								  	allow_destroy: true
 	
 	accepts_nested_attributes_for :directions,
								 	reject_if: proc { |attributes| attributes['step'].blank? },
								  	allow_destroy: true

	acts_as_taggable_on :content, :name, :tag_list
	acts_as_taggable
	acts_as_votable
	extend FriendlyId
	friendly_id :title, use: :slugged

	VALID_REGEX = /\A^[\w \.\-@:),.!?"']*$\Z/
	#VALID_REGEX = /[a-zA-Z0-9\s]/	
	validates :title,  presence: true, length: { maximum: 50 }, format: { with: VALID_REGEX }
	validates :description,  presence: true, length: { maximum: 255 }, format: { with: VALID_REGEX }
	validates :price, length: { maximum: 3 }, :numericality => true, :allow_blank => true
	validates :preparation_time, length: { maximum: 3 }, :numericality => true, :allow_blank => true
	validates :difficulty, :typ, :user_id, presence: true

	def related(mniam)
		mniams = Mniam.all.select {|i| i.typ == mniam.typ and i.id != mniam.id}
		mniams = mniams[0..20]
	end

	def score
    self.get_upvotes.size 
  end

  def self.search(query)
    where("title like ?", "%#{query}%") 
  end

  def self.sort_score
    self.all.sort {|a, b| b.score<=>a.score}
  end

  def self.filtering(type, con)
  	if type.to_i != 0
  		self.all.select{|f| f if f[con] < type.to_i }
  	else
  		self.all.select{|f| f if f[con] == type.to_s }
  	end
  end
end

app/controllers/mniams_controller.rb
class MniamsController < ApplicationController
  before_action :set_mniam, only: [:show, :destroy, :edit, :update, :upvote, :favorite]
  before_action :authenticate_user!, except: [:home]
  load_and_authorize_resource except: [:favorite, :upvote]

  def index
    @search = Mniam.ransack(params[:q])
    @mniams = @search.result.paginate(:page => params[:page], :per_page => 12)  
  end

  def show
    @comments = @mniam.comments.hash_tree
    @comment = @mniam.comments.build(parent_id: params[:parent_id])
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "show",:layout => 'pdf.html.erb',:template => '/mniams/show'  # Excluding ".pdf" extension.
      end
    end
  end

  def new
    @mniam = current_user.mniams.build
  end

  def edit
  end

  def create
    @mniam = current_user.mniams.build(mniam_params)
    if  @mniam.save 
      redirect_to @mniam, notice: "Eat was created"
    else 
      render 'new'
    end
  end

  def update
    if @mniam.update(mniam_params)
      @mniam.save
      redirect_to @mniam, notice: "Eat was updated"
    else
      render 'edit'
    end
  end

  def destroy
    @mniam.destroy
    redirect_to root_path, notice: "Eat was deleted"
  end

  def home
    if params[:search]
      @mniams = Mniam.search(params[:search]).paginate(:page => params[:page], :per_page => 12)  
    elsif params[:tag]
      @mniams = Mniam.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 12)  
    elsif params[:con] && params[:type]
      @mniams = Mniam.filtering(params[:type], params[:con]).paginate(:page => params[:page], :per_page => 12)
    else
      @mniams = Mniam.all.paginate(:page => params[:page], :per_page => 12)  
    end
  end

  def favorite
    if params[:type] == "favorite"
      current_user.favorites << @mniam
      redirect_to mniams_favorite_list_path(current_user), notice: 'You favorited this mniams'
    else
      current_user.favorites.delete(@mniam)
      redirect_to :back, alert: 'Unfavorited this mnians'
    end
  end

  def favorite_list
    @mniams = current_user.favorites.uniq
  end

  def top
    @top = Mniam.sort_score[0..7]
  end

  def upvote 
    @mniam.upvote_by current_user
    redirect_to :back, notice: "You like this Mniams :)"
  end  

  private 

  def set_mniam
    @mniam = Mniam.friendly.find(params[:id])
  end

  def mniam_params
    params.require(:mniam).permit(:title, :description, :avatar, :tag_list, :slug, :price, :difficulty, :typ, :preparation_time,
                                 ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
  end
end

app/helpers/mniams_helper.rb
module MniamsHelper
end

app/views/mniams/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/mniams/_direction_fields.html.erb
<div class="nested-fields">
  <%= f.input :step, input_html: {class: "form-input form-control"} %>
  <%= link_to_remove_association "Remove step", f,  class: "btn btn-default" %>
  <br>
</div>

app/views/mniams/_directions.html.erb
 <h2>Directions</h2>
  <ul>
    <% @mniam.directions.each do |direction| %>
      <li>
        <%= direction.step %>
      </li>
    <% end %>
  </ul>

app/views/mniams/_filter_links.html.erb
<%= link_to filtering_path(f.typ, "typ") do %> <span class="label label-primary"><%= f.typ %></span> <% end%>
<%= link_to filtering_path(f.preparation_time, "preparation_time") do %><span class="label label-primary"><%= f.preparation_time %> min <span class="glyphicon glyphicon-time" aria-hidden="true"></span></span> <% end %>
<%= link_to filtering_path(f.price, "price") do %><span class="label label-primary"><%= f.price %> <span class="glyphicon glyphicon-euro" aria-hidden="true"></span></span> <% end %>
<%= link_to filtering_path(f.difficulty, "difficulty") do %><span class="label label-primary"><%= f.difficulty %> <span class="glyphicon glyphicon-stats" aria-hidden="true"></span></span> <% end%>

app/views/mniams/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
    <%= simple_form_for @mniam, html: { multipart: true } do |f| %>
      <%= render 'shared/errors', :object => @mniam%>
    <div class="col-md-6">
        <%= f.input :avatar, input_html: {class: 'form-control'}%>
    </div>
    <div class="col-md-3">
    <div class="form-group">
      <%= f.label :difficulty %>
      <%= f.select :difficulty, [ "Easy", "Medium", "Hard" ], { :prompt => 'Select One' }, { class: "form-control", :id => "select" } %>
    </div>
    </div>
    <div class="col-md-3">
    <div class="form-group">
        <%= f.label :typ %>
        <%= f.select :typ, [ 'Dinner', 'Breakfast', 'Lunch', 'Snack', 'Diet', 'Dessert'], {:prompt => 'Select One'}, { class: "form-control", :id => "select" } %>
    </div>
    </div>

    <div class="col-md-6">
      <%= f.input :title, input_html: {class: 'form-control'} %>
    </div>

    <div class="col-md-3">
      <%= f.input :price, input_html: {class: 'form-control'}%>
    </div>

    <div class="col-md-3">
      <%= f.input :preparation_time, input_html: {class: 'form-control'}%>
    </div>
    
    <div class="col-md-6">
      <%= f.input :description, input_html: {rows: '1', class: 'form-control'} %>
    </div>

    <div class="col-md-6">
      <%= f.input :tag_list, input_html: {class: 'form-control'}%>
    </div>


    <div class="col-md-6">
      <h3>Ingredients</h3>
      <div id="ingredient">
        <%= f.simple_fields_for :ingredients do |i| %>
          <%= render 'ingredient_fields', f: i %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add ingredient', f, :ingredients, class: "btn btn-success add-button" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Directions</h3>
      <div id="direction">
        <%= f.simple_fields_for :directions do |i| %>
          <%= render 'direction_fields', f: i %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add direction', f, :directions, class: "btn btn-success add-button" %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <br>
    </div>
    <div class="col-md-12">
      <%= link_to "Back", :back, class: "btn btn-default" %>
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
<% end %>
</div>
</div>
</div>
</div>

app/views/mniams/_ingredients.html.erb
<div id="ingredients">
  <h2>Ingredients</h2>
  <ul>
    <% @mniam.ingredients.each do |ingredient| %>
      <li>
        <%= ingredient.name %>
      </li>
    <% end %>
  </ul>
</div>

app/views/mniams/_top_links.html.erb
 <p> 
By: <%= link_to @mniam.user.email,  @mniam.user%> | <b>Score: (<%= @mniam.user.scores(@mniam.user) =%>)</b> | 
<% if user_signed_in? %>
  <%= link_to like_mniam_path(@mniam), method: :put do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
    <%= @mniam.get_upvotes.size %>
  <% end %> |
<%end%> 
  <%= link_to filtering_path(@mniam.typ, "typ") do %> <span class="label label-success"><%= @mniam.typ %></span> <% end%>|
  <%= link_to filtering_path(@mniam.preparation_time, "preparation_time") do %><span class="label label-success"><%= @mniam.preparation_time %> min <span class="glyphicon glyphicon-time" aria-hidden="true"></span></span> <% end %>|
  <%= link_to filtering_path(@mniam.price, "price") do %><span class="label label-success"><%= @mniam.price %> <span class="glyphicon glyphicon-euro" aria-hidden="true"></span></span> <% end %>|
  <%= link_to filtering_path(@mniam.difficulty, "difficulty") do %><span class="label label-success"><%= @mniam.difficulty %> <span class="glyphicon glyphicon-stats" aria-hidden="true"></span></span> <% end%>
</p>

app/views/mniams/edit.html.erb
<% provide(:title, "Edit") %>

<%=	render 'form' %>

app/views/mniams/favorite_list.html.erb
<% provide(:title, "Favorites") %>
 <div class="col-md-6 col-md-offset-3">
 <div class="panel panel-default">
    <div class="panel-body">
<h4>Your favorites list (<%= @mniams.count %>)</h4>
    <% @mniams.each do |f| %>
    <table class="table table-striped table-hover ">
    <tbody>
    <tr class="success">
    <div class="col-md-7">
      <td><%= link_to (image_tag f.avatar.url(:medium), class: "img_small"), f  %>
    </div>
    <div class="col-md-6">
      <h4>
        <%= f.title%>
      </h4>
       <%= link_to "Unfavorite", favorite_mniam_path(f, type: "unfavorite"), method: :put, class: "btn btn-primary" %> </div></td>
      </div>
    </tr>
    </tbody>
    </table>
    <% end %>
</div>
</div>
</div>

app/views/mniams/home.html.erb
<% provide(:title, "Home") %>

<div class="transitions-enabled" id="mniams">
  <% @mniams.each do |f| %>
    <div class="box panel panel-default">
    <div class="hover13 column">
      <figure><%= link_to (image_tag f.avatar.url), f %></figure>
     </div>
      <h2>
        <a><%= link_to f.title, f %></a>
      </h2>
      <p class="user">
        <%= f.description %>
        <hr>
		      <%= render 'filter_links', f: f %>
      </p>
    </div>
  <% end %>
</div>

	<%= will_paginate @mniam %>

app/views/mniams/index.html.erb
<% provide(:title, "Filtering") %>

<%= render 'filter_form' %>

<hr>

<div class="transitions-enabled" id="mniams">
  <% @mniams.each do |f| %>
    <div class="box panel panel-default">
    <div class="hover13 column">
      <figure><%= link_to (image_tag f.avatar.url), f %></figure>
     </div>
      <h2>
        <a><%= link_to f.title, f %></a>
      </h2>
      <p class="user">
        <%= f.description %>
        <hr>
		      <%= render 'filter_links', f: f  %>
      </p>
    </div>
  <% end %>
</div>

<%= will_paginate @mniam %>

app/views/mniams/new.html.erb
<% provide(:title, "New") %>

<%=	render 'form' %>

app/views/mniams/show.pdf.erb
<div class="row">
<div class="col-md-12">
  <h1>Recipe Mmm...</h1>
  <h2><%= @mniam.title %></h2>
  <p><%= @mniam.description %> </p>
  <hr>
</div>

  <div class="col-md-6">
    <div id="ingredients">
      <h2>Ingredients</h2>
      <ul>
        <% @mniam.ingredients.each do |ingredient| %>
          <li>
            <%= ingredient.name %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-6">
    <div id="directions">
      <h2>Directions</h2>
      <ul>
        <% @mniam.directions.each do |direction| %>
          <li>
            <%= direction.step %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

<div class="col-md-12">
<hr>
  <p><b>Price: </b><%= @mniam.price %> Euro </p>
  <p><b>Difficulty: </b> <%=@mniam.difficulty %> </p>
  <p><b>Preparation time: </b><%=@mniam.preparation_time %> min </p>
  <p><b>Type: </b><%=@mniam.typ %> </p>
</div>
</div>

app/views/mniams/top.html.erb
<% provide(:title, "Top") %>

<div class="row">
<div class="col-md-4 col-md-offset-4">
<div class="col-md-12">
  <p style="text-align:center"><%= image_tag('best.png')%></p>
</div> 

<hr>

  <% @top.each_with_index do |f, index| %>
  <table class="table table-striped table-hover ">
    <tbody>
    <tr>
      <td style="text-align:center">
      <br>
        <%= link_to (image_tag f.avatar.url(:medium), class: "top_img"), f %>
      <h2>
        <%= f.title%>
      </h2>
      <p><b>Rank: </b><%=index+1%>
		<span class="label label-primary"><%= f.score %> <span class="glyphicon glyphicon-heart" aria-hidden="true"></span></span></p></td>
      </p>
      </tr>
      </tbody>
      </table>
     
  <% end %>

</div>
</div>