config/routes.rb
Rails.application.routes.draw do
  root "mniams#home" 
  get 'top/tips' => 'tips#top', :as => :top_tips
  get 'static_pages/News'
  get 'static_pages/About'
  get 'static_pages/Contact'
  get 'mniams/home'
  get 'mniams/favorite_list' => 'mniams#favorite_list'
  get 'tags/:tag', to: 'mniams#home', as: :tag
  get '/download_pdf/:id(.:format)' => 'mniams#show', :method => :get, :as=>:show
  get 'feed' => 'users#feed', :as => :feed_list
  get 'top' => 'mniams#top', :as => :top
  get '/filtering/(:type)/(:con)' => 'mniams#home', :as => :filtering

  devise_for :users, controllers: { registrations: 'registrations' } do
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :mniams do
    put :favorite, on: :member
    member do
      put "like", to: "mniams#upvote"
    end
  end

  resources :contacts, only: [:new, :create]
  resources :conversations do
    resources :messages
  end

  resources :tips do
    member do
      put "like", to: "tips#upvote"
    end
  end

  resources :users, :only => [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create]
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable  # uncomment in production REMEBER THAT!

  has_many :mniams, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tips, dependent: :destroy
  has_attached_file :user_avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://logocache.com/custom-design/logo-name/1533867-designstyle-chess-m.png"
  validates_attachment_content_type :user_avatar, content_type: /\Aimage\/.*\Z/ 
  has_many :favorite_recipes  
  has_many :favorites, through: :favorite_recipes, source: :mniam

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :conversations, :foreign_key => :sender_id, dependent: :destroy

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Mniam.where("user_id IN (#{following_ids})", user_id: id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def scores(user)
    s = 0
    user.mniams.each do |f|
      s += f.get_upvotes.size
    end
    s 
  end

  def self.sort_score
    self.all.sort {|a, b| b.scores(b)<=>a.scores(a)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :search_user, only: [:show, :destroy, :following, :followers]
	before_action :authenticate_user!

	def show
	end

	def index 
    @users = User.sort_score
    @conversations = Conversation.involving(current_user).order("created_at DESC") 
	end

	def destroy
	  @user.destroy
	  redirect_to users_path, alert: "User was deleted"
  end

  def following
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def feed
  	@feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 15)  
  end

  private

    def search_user 
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/users/_foll.html.erb
<h3><%= @user.email %></h3>
  <p><%= @user.desc %></p>
  <div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user_mniams.html.erb
<h4>All mniams:</h4>
<% @user.mniams.each do |f| %>
  <%= link_to (image_tag f.avatar.url(:medium), class: "img_related"),f  %>
<% end %>

app/views/users/feed.html.erb
<% provide(:title, "Feed") %>

<div class="transitions-enabled" id="mniams">
  <% @feed_items.each do |f| %>
    <div class="box panel panel-default">
    <div class="hover13 column">
      <figure><%= link_to (image_tag f.avatar.url), f %></figure>
     </div>
      <h2>
        <a><%= link_to f.title, f %></a>
      </h2>
      Submited by: <p><%= link_to f.user.email, f.user %></p>
    </div>
  <% end %>
</div>

<%= will_paginate @feed_items %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>

<div class="col-md-12">
  <p style="text-align:center"><%= link_to image_tag('logo44.png'), root_path %></p>
</div>


<div class="col-md-8 col-md-offset-2">
<div class="panel panel-default">
  <div class="panel-body">
 

<div class="col-md-12">
<table class="table table-striped table-hover ">
<% @users.each_with_index do |user, index| %> 
<tr >
<div class="col-md-6">
	<td><%=index+1%>. 
  <%= (image_tag user.user_avatar.url(:medium), class: "img_related") %>
  <%= link_to user.email, user %> <b>Score: (<%= user.scores(user) %>)</b>
  <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation", "data-sid" => current_user.id, "data-rip" => user.id %>
	<% if current_user.admin? %>
  		<%= link_to "Delete", user, method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-default" %> </td>
	<%end%> 
  </tr>
<% end %>
</table>
</div>
</div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
<h3>Your Conversations</h3>
  <hr>
    <div style="height: 400px; overflow-y: auto;">
      <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <% if User.find_by id: conversation.recipient_id %>
                      <%= image_tag(User.find(conversation.recipient_id).user_avatar.url, class: "img_related media-object pull-left") %>
                      <div class="media-body">
                        <%= User.find(conversation.recipient_id).email%>  
                        <%= link_to "Reply", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                      </div> 
                  <% end %>
                </li>
            <% end %>
          </ul>
      <% else %>
          <p>You have no conversations. Click send message with any user to create one.</p>
      <% end %>
    </div>
  </div>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-body">

<div class="col-md-6">
  <%= (image_tag @user.user_avatar.url(:medium), class: "user_img") %>
</div>

<div class="col-md-6">
  <%= render 'foll' %>
</div>
<hr>

<div class="col-md-6">
  <br>
  <%= social_share_button_tag(@user.email) %>
</div>

<div class="col-md-6">
  <%= render 'follow_form' if signed_in? %> 
</div>
<div class="col-md-12">
  <%= render 'user_mniams' %>
</div>

<div class="col-md-12">
<hr>
<%= link_to "Back", users_path, class: "btn btn-default" %>
<% if @user == current_user %>
  <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-primary" %>
<% end %>
</div>
</div>
</div>
</div>

app/views/users/show_follow.html.erb
 <% provide(:title, @title) %>

<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-body">


<div class="col-md-5">
  <%= (image_tag @user.user_avatar.url(:medium), class: "user_img") %>
</div>

<div class="col-md-7">
 <h1><%= @user.email %></h1>
 <span><%= link_to "view my profile", @user, class: "btn btn-primary" %></span>
</div>

<div class="col-md-12">
<br>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>
<hr>
</div>

<div class="col-md-12">
<% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |f| %>
            <%= link_to (image_tag f.user_avatar.url(:medium), class: "img_related"),f  %>
          <% end %>
        </div>
      <% end %>
</div>
</div>
</div>
</div>