config/routes.rb
Rails.application.routes.draw do
  root "mniams#home" 
  get 'top/tips' => 'tips#top', :as => :top_tips
  get 'static_pages/News'
  get 'static_pages/About'
  get 'static_pages/Contact'
  get 'mniams/home'
  get 'mniams/favorite_list' => 'mniams#favorite_list'
  get 'tags/:tag', to: 'mniams#home', as: :tag
  get '/download_pdf/:id(.:format)' => 'mniams#show', :method => :get, :as=>:show
  get 'feed' => 'users#feed', :as => :feed_list
  get 'top' => 'mniams#top', :as => :top
  get '/filtering/(:type)/(:con)' => 'mniams#home', :as => :filtering

  devise_for :users, controllers: { registrations: 'registrations' } do
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :mniams do
    put :favorite, on: :member
    member do
      put "like", to: "mniams#upvote"
    end
  end

  resources :contacts, only: [:new, :create]
  resources :conversations do
    resources :messages
  end

  resources :tips do
    member do
      put "like", to: "tips#upvote"
    end
  end

  resources :users, :only => [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create]
end

app/views/shared/_errors.html.erb
<% if @mniam.errors.any? %>
  <p class="alert alert-error">Ooops!</p>
  <ul>
    <% @mniam.errors.each do |msg| %>
      <li class="error"><%= msg %></li>
    <% end %>
  </ul> 
<% end %>

app/views/shared/_footer.html.erb
<div class ="row">
<div class="col-md-12">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png'), mniams_home_path, :class => "logo" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= static_pages_News_path %>">News</a></li>
        <li><a href="<%= static_pages_About_path %>">About</a></li>
        <li><a href="<%= new_contact_path %>">Contact</a></li>
      </ul>  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  <br>
<br>
<br>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png'), root_path, :class => "logo" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= mniams_path %>">Filter</a></li>
            <li><a href="<%= top_path %>">Top</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="<%= mniams_favorite_list_path(current_user) %>">Favorites</a></li>
            <li><a href="<%= feed_list_path %>">Feed</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="<%= tips_path %>">Tip</a></li>
          </ul>
        </li>

  
    <%= form_tag(root_path, :method => "get", class: "navbar-form navbar-left", id: "search") do %>
      <div class="input-append">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search..." %>
      </div>
    <% end %>

        <li><a href="<%= new_mniam_path %>">New</a></li>
        <li class="dropdown">

        <% if user_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= user_path(current_user) %>">Profile</a></li>
            <li><a href="<%= users_path %>">Users</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><a href="<%= new_user_registration_path %>">Sign in</a></li>
          <li><a href="<%= new_user_session_path %>">Sign up</a></li>
        <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>