config/routes.rb
Rails.application.routes.draw do
  root "mniams#home" 
  get 'top/tips' => 'tips#top', :as => :top_tips
  get 'static_pages/News'
  get 'static_pages/About'
  get 'static_pages/Contact'
  get 'mniams/home'
  get 'mniams/favorite_list' => 'mniams#favorite_list'
  get 'tags/:tag', to: 'mniams#home', as: :tag
  get '/download_pdf/:id(.:format)' => 'mniams#show', :method => :get, :as=>:show
  get 'feed' => 'users#feed', :as => :feed_list
  get 'top' => 'mniams#top', :as => :top
  get '/filtering/(:type)/(:con)' => 'mniams#home', :as => :filtering

  devise_for :users, controllers: { registrations: 'registrations' } do
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :mniams do
    put :favorite, on: :member
    member do
      put "like", to: "mniams#upvote"
    end
  end

  resources :contacts, only: [:new, :create]
  resources :conversations do
    resources :messages
  end

  resources :tips do
    member do
      put "like", to: "tips#upvote"
    end
  end

  resources :users, :only => [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create]
end

app/models/tip.rb
class Tip < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :user_id, :category, presence: true
	VALID_REGEX = /\A^[\w \.\-@:),.!?"']*$\Z/
	validates :title, presence: true, length: { in: 3..70 }, format: { with: VALID_REGEX }
	validates :description, presence: true, length: { in: 10..400 }, format: { with: VALID_REGEX }
	validates :movie, presence: true, length: { maximum: 50 }
	
	acts_as_votable

	def self.score
    self.get_upvotes.size 
  end

  def self.the_best
  	self.all.sort {|a, b| b.score<=>a.score}
  end

  def self.set_category(cat)
  	self.all.select {|a| a if a.category == cat}
  end
end
 

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  require 'will_paginate/array' 
  load_and_authorize_resource except: [:upvote]
  before_action :find_tip, only: [:show, :upvote, :edit, :destroy, :update]
	before_action :authenticate_user!

  def index
    @search = Tip.ransack(params[:q])
    @tips = @search.result.order("created_at DESC").paginate(:page => params[:page], :per_page => 7)  
    if (params[:format])
      @tips = Tip.set_category(params[:format].to_s).paginate(:page => params[:page], :per_page => 7)  
    end
  end

  def show
    @comments = @tip.comments.hash_tree
    @comment = @tip.comments.build(parent_id: params[:parent_id])
  end

  def new
  	@tip = current_user.tips.build
  end 

  def create
  	@tip = current_user.tips.build(tip_params)
    @tip.movie = movie_conventer
    if @tip.save 
      redirect_to tips_path, notice: "Tip was created"
    else 
      render 'new'
    end
  end

  def edit
  end

  def update
    if @tip.update(tip_params)
      @tip.movie = movie_conventer
      @tip.save
      redirect_to @tip, notice: "Tip was updated"
    else
      render 'edit'
    end
  end

  def destroy
    @tip.destroy
    redirect_to tips_path, notice: "Tip was deleted"
  end

  def top
    @tips = Tip.the_best[0..4]
  end

  def movie_conventer
    yt_id = @tip.movie[@tip.movie.length-11...@tip.movie.length]
    yt_id.nil? ? yt = "" : yt = "https://www.youtube.com/embed/" + yt_id
  end

  def upvote 
    @tip.upvote_by current_user
    redirect_to :back, notice: "You like this Tip :)"
  end 

  private

    def tip_params
    	params.require(:tip).permit(:movie, :title, :description, :user_id, :category)
    end

    def find_tip
      @tip = Tip.find(params[:id])
    end
end

app/helpers/tips_helper.rb
module TipsHelper
	
end

app/views/tips/_comments.html.erb
<h4><b>Comments: (<%= @tip.comments.count %>)</b></h4>
  Add a comment!
  <%= form_for @comment do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :tip_id %>
    <%= f.hidden_field :parent_id %>

    <div class="form-group">
      <%= f.text_area :body, class: 'form-control', required: true %>
    </div>
    

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
  <hr>

app/views/tips/_filter_form.html.erb
<div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
          <div class="col-md-4">
               <%= search_form_for @search do |f| %>
                <%= f.select :category_eq, [ 'Tip','Dinner', 'Breakfast', 'Lunch', 'Snack', 'Diet', 'Dessert'], {:prompt => 'Select One'},{ class: "form-control", :id => "select" } %>
          </div>
          <div class="col-md-6">      
              <%= f.submit "Search", class: "btn btn-primary" %> |
              <% end %>
              <%= link_to "Top", top_tips_path, class: "btn btn-primary" %>
              | <%= link_to "+", new_tip_path, class: "btn btn-primary" %>
          </div>
      </div>
    </div>
 </div>

app/views/tips/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
    <%= simple_form_for @tip, html: { multipart: true } do |f| %>

     <div class="col-md-12">
      <%= f.input :title, input_html: {class: 'form-control'} %>
    </div>

     <div class="col-md-6">
      <%= f.input :movie, input_html: {class: 'form-control'}%>
    </div>

    <div class="col-md-6">
    <%= f.label :category %>
        <%= f.select :category, [ 'Tip', 'Dinner', 'Breakfast', 'Lunch', 'Snack', 'Diet', 'Dessert'], {:prompt => 'Select One'}, { class: "form-control", :id => "select" } %>
    </div>

	   <div class="col-md-12">
      <%= f.input :description, input_html: {class: 'form-control'}%>
    </div>

    <div class="col-md-12">
      <%= link_to "Back", :back, class: "btn btn-default" %>
      <%= f.button :submit, class: "btn btn-primary" %>
  	</div>

   	<% end %>
    </div>
  </div>
</div>

app/views/tips/edit.html.erb
<% provide(:title, "Edit Tip" ) %>

<%= render 'form' %>

app/views/tips/index.html.erb
<% provide(:title, "Tips") %>

<div class="col-md-10 col-md-offset-1">
    <%= render 'filter_form' %>
    <hr>
<div class="panel panel-default">
    <div class="panel-body">
        <h4>Tips (<%= @tips.count %>)</h4>

        <% @tips.each do |f| %>
        <table class="table table-striped table-hover ">
        <div class="row">
            <tbody>
            <tr class="success">
                <td>
                    <div class="col-md-12">
                    <br>
                    	<p>
                	    	Created at: <%= link_to f.user.email,  f.user, class: "aaa"%> | 		
                	    	<%= link_to tips_path(f.category) do %> <span class="label label-primary"><%= f.category %> <span class="glyphicon glyphicon-flag" aria-hidden="true"></span></span><%end%> |  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>(<%= f.get_upvotes.size %>)
                		</p>
                    </div>
                    <div class="col-md-9">
                    	<h3><%= f.title %></h3>
                    </div>
                    
                    <div class="col-md-3">
                    	<%= link_to "Watch Movie", f, class: "btn btn-primary" %>
                    </div>
             	</td>
            </tr>
            </tbody>
        </table>
        <% end %>
    </div>
</div>
</div>
<%= will_paginate @tips %>

app/views/tips/new.html.erb
<% provide(:title, "New Tip" ) %>

<%= render 'form' %>

app/views/tips/show.html.erb
<% provide(:title, @tip.title ) %>

<div class="col-md-12">
	<p style="text-align:center"><%= link_to image_tag('logo4.png'), tips_path %></p>
</div>

<div class="col-md-8 col-md-offset-2">
	<div class="panel panel-default">
    <div class="panel-body">
		<div class="col-md-12">
					<br>
					<p>
			    	Created at: <%= link_to @tip.user.email,  @tip.user%> | 		
			    	<%= link_to tips_path(@tip.category) do %> <span class="label label-success"><%= @tip.category %> <span class="glyphicon glyphicon-flag" aria-hidden="true"></span></span><%end%> | 
					  <% if user_signed_in? %>
					    <%= link_to like_tip_path(@tip), method: :put do %>
					      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
					      <b>(<%= @tip.get_upvotes.size %>)</b>
					    <% end %>
					  <%end%> 
					</p>
				</div>


				<div class="col-md-12">
					<h3><%= @tip.title %></h3>
				</div>

				<div class="col-md-12">
					<iframe width="690" height="380" src="<%= @tip.movie %>" frameborder="0" allowfullscreen></iframe> 
				</div>

				<div class="col-md-12">
					<h4><%= @tip.description %></h4>
				</div>
	
				<div class="col-md-12">
					<%= social_share_button_tag(@tip.title) %>
					<hr>
						<%= link_to "Back", tips_path, class: "btn btn-primary" %>
						<% if @tip.user == current_user  or current_user.admin?%>
					    <%= link_to "Edit", edit_tip_path(@tip), class: "btn btn-default" %>
					    <%= link_to "Delete", tip_path, method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-default" %>
					<%end%> 
					<br>
				</div>

				<div class="col-md-12">
					<%= render 'comments' %>
					<%= comments_tree_for @comments %>
				</div>

			</div>
		</div>
	</div>

app/views/tips/top.html.erb
<% provide(:title, "Top tips") %>

<div class="col-md-12">
  <p style="text-align:center"><%= image_tag('best.png')%></p>
</div> 

<div class="col-md-10 col-md-offset-1">
<div class="panel panel-default">
  <div class="panel-body">

<% @tips.each do |f| %>
<table class="table table-striped table-hover ">
<div class="row">
    <tbody>
    <tr class="success">
    <td>
    <div class="col-md-12">
    <br>
    	<p>
	    	Created at: <%= link_to f.user.email,  f.user, class: "aaa"%> | 		
	    	<%= link_to filtering_tips_path(f.category) do %> <span class="label label-primary"><%= f.category %> <span class="glyphicon glyphicon-flag" aria-hidden="true"></span></span><%end%>  |  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> (<%= f.get_upvotes.size %>)
		</p>
    </div>
    <div class="col-md-9">
    	<h3><%= f.title %></h3>
    </div>
    
    <div class="col-md-3">
    	<%= link_to "Watch Movie", f, class: "btn btn-primary" %>
    </div>
 	</td>
    </tr>
    </tbody>
    </table>
    <% end %>
    
        <hr>
        <%= link_to "Back", tips_path, class: "btn btn-primary" %>
    
</div>
</div>
</div>